config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :posts do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { in: 1..600 }
  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255},
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6}
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if params[:back]
      render :new
    else
      if @post.save
        redirect_to user_path(current_user.id), notice: "投稿を作成しました"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "投稿を編集しました"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice:"投稿を削除しました"
  end
  def confirm
    @post = current_user.posts.build(post_params)
    render :new if @post.invalid?
  end

  private
  def post_params
    params.require(:post).permit(:content, :image, :image_cache)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: "アカウントを作成しました、ログインしてください！"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Footnote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-dark bg-primary">
      <div class="container">
        <div class="nabar-header">
          <h1>Footnote</h1>
          <button type="button" class="btn">
          <%= link_to "Time line", posts_path %>
          </button>
          <nav class="navbar-right">
          <% flash.each do |key,value| %>
            <%= content_tag(:div, value, class:"#{key}") %>
          <% end %>
            <% if logged_in? %>
              <p><%= current_user.name %>さんがログイン中</p>
              <button type="button" class="btn">
              <%= link_to "New post", new_post_path %>
              </button>
              <button type="button" class="btn">
              <%= link_to "My page", user_path(current_user.id) %>
              </button>
              <button type="button" class="btn">
              <%= link_to "Log out", session_path(current_user.id), method: :delete %>
              </button>
            <% else %>
              <button type="button" class="btn">
              <%= link_to "Sign Up", new_user_path %>
              </button>
              <button type="button" class="btn">
              <%= link_to "Log in", new_session_path %>
              </button>
            <% end %>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
    <%= yield %>
    </div>
    <footer class="footer">
      <div class="container">
        <p class="text-muted">Copyright © 2021 WEF2101 Kajiyama Yuuki.</p>
      </div>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true, url: choose_new_or_edit ) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
    <%= form.text_area :content %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/confirm.html.erb
<h3>Are you sure post?</h3>
  <%= form_with(model: @post, local: true, url: choose_new_or_edit) do |form| %>
    <%= form.hidden_field :content %>
    <p>Post:<%= @post.content %></p>
    <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit %>
    <%= form.submit "back", name: 'back' %>
  <% end %>

app/views/posts/edit.html.erb
<h2>投稿編集<h2>
<%= render 'form' %>

app/views/posts/index.html.erb
<h2>投稿一覧</h2>
<table class="table">
  <thead>
    <tr class="row">
      <th class="col-md-1" scope="col">User</th>
      <th class="col-md-8" scope="col">Post</th>
      <th class="col-md-2" scope="col">image</th>
      <th class="col-md-1" scope="col">Command</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr class="tweet row" scope="row">
        <td class="user col-lg-1"><%= post.user.name %></td>
        <td class="post col-lg-8"><%= post.content %></td>
        <td class="post col-lg-2"><%= "(画像有り)" if post.image.present? %></td>
        <td class="command col-lg-1"><%= link_to 'Show', post_path(post) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h2>新規投稿<h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>投稿詳細画面</h1>
<p>投稿者: <%= @post.user.name %></p>
<p>内容: <%= @post.content %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @post.image.url if @post.image.present? %>
</p>

<% if current_user.present? && @post.user_id == current_user.id %>
  <%= link_to 'Edit', edit_post_path(@post), data: { confirm: 'Are you sure edit?'} %>
  <%= link_to 'Destroy', post_path(@post), method: :delete, data: { confirm: 'Are you sure delete?' } %>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<% if @user.errors.any? %>
  <div id = "error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |form| %>
  <%= form.label :name %><br>
  <%= form.text_field :name %><br>
  <%= form.label :email %><br>
  <%= form.email_field :email %><br>
  <%= form.label :password %><br>
  <%= form.password_field :password %><br>
  <%= form.label :password_confirmation %><br>
  <%= form.password_field :password_confirmation %>
  <%= form.submit "create new account!" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>さんのページ</h1>
<% @posts.each do |post| %>
  <hr>
  <p><span>投稿内容: </span><%=link_to post.content, post_path(post.id) %><%= "(画像有り)" if post.image.present? %></p>
<% end %>